server:
  port: 6666

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wkmtem/interview-config.git
          username: wkmtem
          password: 19870925yjcsxdl


# 请求配置文件的规则如下：
# /{application}/{profile}/[label]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties
# 其中{label}是指分支，默认是master

# gitHub 命令
# echo "# interview-config" >> README.md
# git init
# git add README.md
# git commit -m "first commit"
# git remote add origin https://github.com/wkmtem/interview-config.git
# git push -u origin master